spring.application.name=backend-project
spring.datasource.url=jdbc:postgresql://localhost:5432/backendProject
spring.datasource.username=postgres
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
